/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: trade_side_agnostic_aggregation.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./timestamp/timestamp";
import * as pb_1 from "google-protobuf";
export class TradeSideAgnosticAggregation extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        open?: number;
        high?: number;
        low?: number;
        close?: number;
        volume?: number;
        timestamp?: dependency_1.Timestamp;
        firstTimestamp?: dependency_1.Timestamp;
        lastTimestamp?: dependency_1.Timestamp;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("open" in data && data.open != undefined) {
                this.open = data.open;
            }
            if ("high" in data && data.high != undefined) {
                this.high = data.high;
            }
            if ("low" in data && data.low != undefined) {
                this.low = data.low;
            }
            if ("close" in data && data.close != undefined) {
                this.close = data.close;
            }
            if ("volume" in data && data.volume != undefined) {
                this.volume = data.volume;
            }
            if ("timestamp" in data && data.timestamp != undefined) {
                this.timestamp = data.timestamp;
            }
            if ("firstTimestamp" in data && data.firstTimestamp != undefined) {
                this.firstTimestamp = data.firstTimestamp;
            }
            if ("lastTimestamp" in data && data.lastTimestamp != undefined) {
                this.lastTimestamp = data.lastTimestamp;
            }
        }
    }
    get open() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set open(value: number) {
        pb_1.Message.setField(this, 1, value);
    }
    get high() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set high(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    get low() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set low(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    get close() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
    }
    set close(value: number) {
        pb_1.Message.setField(this, 4, value);
    }
    get volume() {
        return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
    }
    set volume(value: number) {
        pb_1.Message.setField(this, 5, value);
    }
    get timestamp() {
        return pb_1.Message.getWrapperField(this, dependency_1.Timestamp, 6) as dependency_1.Timestamp;
    }
    set timestamp(value: dependency_1.Timestamp) {
        pb_1.Message.setWrapperField(this, 6, value);
    }
    get has_timestamp() {
        return pb_1.Message.getField(this, 6) != null;
    }
    get firstTimestamp() {
        return pb_1.Message.getWrapperField(this, dependency_1.Timestamp, 7) as dependency_1.Timestamp;
    }
    set firstTimestamp(value: dependency_1.Timestamp) {
        pb_1.Message.setWrapperField(this, 7, value);
    }
    get has_firstTimestamp() {
        return pb_1.Message.getField(this, 7) != null;
    }
    get lastTimestamp() {
        return pb_1.Message.getWrapperField(this, dependency_1.Timestamp, 8) as dependency_1.Timestamp;
    }
    set lastTimestamp(value: dependency_1.Timestamp) {
        pb_1.Message.setWrapperField(this, 8, value);
    }
    get has_lastTimestamp() {
        return pb_1.Message.getField(this, 8) != null;
    }
    static fromObject(data: {
        open?: number;
        high?: number;
        low?: number;
        close?: number;
        volume?: number;
        timestamp?: ReturnType<typeof dependency_1.Timestamp.prototype.toObject>;
        firstTimestamp?: ReturnType<typeof dependency_1.Timestamp.prototype.toObject>;
        lastTimestamp?: ReturnType<typeof dependency_1.Timestamp.prototype.toObject>;
    }): TradeSideAgnosticAggregation {
        const message = new TradeSideAgnosticAggregation({});
        if (data.open != null) {
            message.open = data.open;
        }
        if (data.high != null) {
            message.high = data.high;
        }
        if (data.low != null) {
            message.low = data.low;
        }
        if (data.close != null) {
            message.close = data.close;
        }
        if (data.volume != null) {
            message.volume = data.volume;
        }
        if (data.timestamp != null) {
            message.timestamp = dependency_1.Timestamp.fromObject(data.timestamp);
        }
        if (data.firstTimestamp != null) {
            message.firstTimestamp = dependency_1.Timestamp.fromObject(data.firstTimestamp);
        }
        if (data.lastTimestamp != null) {
            message.lastTimestamp = dependency_1.Timestamp.fromObject(data.lastTimestamp);
        }
        return message;
    }
    toObject() {
        const data: {
            open?: number;
            high?: number;
            low?: number;
            close?: number;
            volume?: number;
            timestamp?: ReturnType<typeof dependency_1.Timestamp.prototype.toObject>;
            firstTimestamp?: ReturnType<typeof dependency_1.Timestamp.prototype.toObject>;
            lastTimestamp?: ReturnType<typeof dependency_1.Timestamp.prototype.toObject>;
        } = {};
        if (this.open != null) {
            data.open = this.open;
        }
        if (this.high != null) {
            data.high = this.high;
        }
        if (this.low != null) {
            data.low = this.low;
        }
        if (this.close != null) {
            data.close = this.close;
        }
        if (this.volume != null) {
            data.volume = this.volume;
        }
        if (this.timestamp != null) {
            data.timestamp = this.timestamp.toObject();
        }
        if (this.firstTimestamp != null) {
            data.firstTimestamp = this.firstTimestamp.toObject();
        }
        if (this.lastTimestamp != null) {
            data.lastTimestamp = this.lastTimestamp.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.open != 0)
            writer.writeDouble(1, this.open);
        if (this.high != 0)
            writer.writeDouble(2, this.high);
        if (this.low != 0)
            writer.writeDouble(3, this.low);
        if (this.close != 0)
            writer.writeDouble(4, this.close);
        if (this.volume != 0)
            writer.writeDouble(5, this.volume);
        if (this.has_timestamp)
            writer.writeMessage(6, this.timestamp, () => this.timestamp.serialize(writer));
        if (this.has_firstTimestamp)
            writer.writeMessage(7, this.firstTimestamp, () => this.firstTimestamp.serialize(writer));
        if (this.has_lastTimestamp)
            writer.writeMessage(8, this.lastTimestamp, () => this.lastTimestamp.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TradeSideAgnosticAggregation {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TradeSideAgnosticAggregation();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.open = reader.readDouble();
                    break;
                case 2:
                    message.high = reader.readDouble();
                    break;
                case 3:
                    message.low = reader.readDouble();
                    break;
                case 4:
                    message.close = reader.readDouble();
                    break;
                case 5:
                    message.volume = reader.readDouble();
                    break;
                case 6:
                    reader.readMessage(message.timestamp, () => message.timestamp = dependency_1.Timestamp.deserialize(reader));
                    break;
                case 7:
                    reader.readMessage(message.firstTimestamp, () => message.firstTimestamp = dependency_1.Timestamp.deserialize(reader));
                    break;
                case 8:
                    reader.readMessage(message.lastTimestamp, () => message.lastTimestamp = dependency_1.Timestamp.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): TradeSideAgnosticAggregation {
        return TradeSideAgnosticAggregation.deserialize(bytes);
    }
}
