// source: cme_open_interest_aggregation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var timestamp_timestamp_pb = require('./timestamp/timestamp_pb.js');
goog.object.extend(proto, timestamp_timestamp_pb);
goog.exportSymbol('proto.CmeOpenInterestAggregation', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CmeOpenInterestAggregation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CmeOpenInterestAggregation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CmeOpenInterestAggregation.displayName = 'proto.CmeOpenInterestAggregation';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CmeOpenInterestAggregation.prototype.toObject = function(opt_includeInstance) {
  return proto.CmeOpenInterestAggregation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CmeOpenInterestAggregation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CmeOpenInterestAggregation.toObject = function(includeInstance, msg) {
  var f, obj = {
    open: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    high: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    low: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    close: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    valueopen: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    valuehigh: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    valuelow: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    valueclose: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    priceopen: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    pricehigh: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
    pricelow: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0),
    priceclose: jspb.Message.getFloatingPointFieldWithDefault(msg, 12, 0.0),
    timestamp: (f = msg.getTimestamp()) && timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CmeOpenInterestAggregation}
 */
proto.CmeOpenInterestAggregation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CmeOpenInterestAggregation;
  return proto.CmeOpenInterestAggregation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CmeOpenInterestAggregation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CmeOpenInterestAggregation}
 */
proto.CmeOpenInterestAggregation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOpen(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setHigh(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLow(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setClose(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValueopen(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValuehigh(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValuelow(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValueclose(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPriceopen(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPricehigh(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPricelow(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPriceclose(value);
      break;
    case 13:
      var value = new timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CmeOpenInterestAggregation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CmeOpenInterestAggregation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CmeOpenInterestAggregation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CmeOpenInterestAggregation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeDouble(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeDouble(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeDouble(
      11,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeDouble(
      12,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional double open = 1;
 * @return {number}
 */
proto.CmeOpenInterestAggregation.prototype.getOpen = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.setOpen = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.clearOpen = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CmeOpenInterestAggregation.prototype.hasOpen = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional double high = 2;
 * @return {number}
 */
proto.CmeOpenInterestAggregation.prototype.getHigh = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.setHigh = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.clearHigh = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CmeOpenInterestAggregation.prototype.hasHigh = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional double low = 3;
 * @return {number}
 */
proto.CmeOpenInterestAggregation.prototype.getLow = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.setLow = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.clearLow = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CmeOpenInterestAggregation.prototype.hasLow = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional double close = 4;
 * @return {number}
 */
proto.CmeOpenInterestAggregation.prototype.getClose = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.setClose = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.clearClose = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CmeOpenInterestAggregation.prototype.hasClose = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional double valueOpen = 5;
 * @return {number}
 */
proto.CmeOpenInterestAggregation.prototype.getValueopen = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.setValueopen = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.clearValueopen = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CmeOpenInterestAggregation.prototype.hasValueopen = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional double valueHigh = 6;
 * @return {number}
 */
proto.CmeOpenInterestAggregation.prototype.getValuehigh = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.setValuehigh = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.clearValuehigh = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CmeOpenInterestAggregation.prototype.hasValuehigh = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional double valueLow = 7;
 * @return {number}
 */
proto.CmeOpenInterestAggregation.prototype.getValuelow = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.setValuelow = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.clearValuelow = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CmeOpenInterestAggregation.prototype.hasValuelow = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional double valueClose = 8;
 * @return {number}
 */
proto.CmeOpenInterestAggregation.prototype.getValueclose = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.setValueclose = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.clearValueclose = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CmeOpenInterestAggregation.prototype.hasValueclose = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional double priceOpen = 9;
 * @return {number}
 */
proto.CmeOpenInterestAggregation.prototype.getPriceopen = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.setPriceopen = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.clearPriceopen = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CmeOpenInterestAggregation.prototype.hasPriceopen = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional double priceHigh = 10;
 * @return {number}
 */
proto.CmeOpenInterestAggregation.prototype.getPricehigh = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.setPricehigh = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.clearPricehigh = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CmeOpenInterestAggregation.prototype.hasPricehigh = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional double priceLow = 11;
 * @return {number}
 */
proto.CmeOpenInterestAggregation.prototype.getPricelow = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.setPricelow = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.clearPricelow = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CmeOpenInterestAggregation.prototype.hasPricelow = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional double priceClose = 12;
 * @return {number}
 */
proto.CmeOpenInterestAggregation.prototype.getPriceclose = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 12, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.setPriceclose = function(value) {
  return jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.clearPriceclose = function() {
  return jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CmeOpenInterestAggregation.prototype.hasPriceclose = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional Timestamp timestamp = 13;
 * @return {?proto.Timestamp}
 */
proto.CmeOpenInterestAggregation.prototype.getTimestamp = function() {
  return /** @type{?proto.Timestamp} */ (
    jspb.Message.getWrapperField(this, timestamp_timestamp_pb.Timestamp, 13));
};


/**
 * @param {?proto.Timestamp|undefined} value
 * @return {!proto.CmeOpenInterestAggregation} returns this
*/
proto.CmeOpenInterestAggregation.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.CmeOpenInterestAggregation} returns this
 */
proto.CmeOpenInterestAggregation.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CmeOpenInterestAggregation.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 13) != null;
};


goog.object.extend(exports, proto);
