// source: funding_rate_aggregation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var timestamp_timestamp_pb = require('./timestamp/timestamp_pb.js');
goog.object.extend(proto, timestamp_timestamp_pb);
goog.exportSymbol('proto.FundingRateAggregation', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.FundingRateAggregation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.FundingRateAggregation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.FundingRateAggregation.displayName = 'proto.FundingRateAggregation';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.FundingRateAggregation.prototype.toObject = function(opt_includeInstance) {
  return proto.FundingRateAggregation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.FundingRateAggregation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FundingRateAggregation.toObject = function(includeInstance, msg) {
  var f, obj = {
    rateopen: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    ratehigh: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    ratelow: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    rateclose: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    predictedopen: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    predictedhigh: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    predictedlow: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    predictedclose: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    timestamp: (f = msg.getTimestamp()) && timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.FundingRateAggregation}
 */
proto.FundingRateAggregation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.FundingRateAggregation;
  return proto.FundingRateAggregation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.FundingRateAggregation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.FundingRateAggregation}
 */
proto.FundingRateAggregation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setRateopen(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setRatehigh(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setRatelow(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setRateclose(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPredictedopen(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPredictedhigh(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPredictedlow(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPredictedclose(value);
      break;
    case 9:
      var value = new timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.FundingRateAggregation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.FundingRateAggregation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.FundingRateAggregation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FundingRateAggregation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional double rateOpen = 1;
 * @return {number}
 */
proto.FundingRateAggregation.prototype.getRateopen = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.setRateopen = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.clearRateopen = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.FundingRateAggregation.prototype.hasRateopen = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional double rateHigh = 2;
 * @return {number}
 */
proto.FundingRateAggregation.prototype.getRatehigh = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.setRatehigh = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.clearRatehigh = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.FundingRateAggregation.prototype.hasRatehigh = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional double rateLow = 3;
 * @return {number}
 */
proto.FundingRateAggregation.prototype.getRatelow = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.setRatelow = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.clearRatelow = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.FundingRateAggregation.prototype.hasRatelow = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional double rateClose = 4;
 * @return {number}
 */
proto.FundingRateAggregation.prototype.getRateclose = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.setRateclose = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.clearRateclose = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.FundingRateAggregation.prototype.hasRateclose = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional double predictedOpen = 5;
 * @return {number}
 */
proto.FundingRateAggregation.prototype.getPredictedopen = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.setPredictedopen = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.clearPredictedopen = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.FundingRateAggregation.prototype.hasPredictedopen = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional double predictedHigh = 6;
 * @return {number}
 */
proto.FundingRateAggregation.prototype.getPredictedhigh = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.setPredictedhigh = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.clearPredictedhigh = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.FundingRateAggregation.prototype.hasPredictedhigh = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional double predictedLow = 7;
 * @return {number}
 */
proto.FundingRateAggregation.prototype.getPredictedlow = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.setPredictedlow = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.clearPredictedlow = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.FundingRateAggregation.prototype.hasPredictedlow = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional double predictedClose = 8;
 * @return {number}
 */
proto.FundingRateAggregation.prototype.getPredictedclose = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.setPredictedclose = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.clearPredictedclose = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.FundingRateAggregation.prototype.hasPredictedclose = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional Timestamp timestamp = 9;
 * @return {?proto.Timestamp}
 */
proto.FundingRateAggregation.prototype.getTimestamp = function() {
  return /** @type{?proto.Timestamp} */ (
    jspb.Message.getWrapperField(this, timestamp_timestamp_pb.Timestamp, 9));
};


/**
 * @param {?proto.Timestamp|undefined} value
 * @return {!proto.FundingRateAggregation} returns this
*/
proto.FundingRateAggregation.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.FundingRateAggregation} returns this
 */
proto.FundingRateAggregation.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.FundingRateAggregation.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 9) != null;
};


goog.object.extend(exports, proto);
