// source: hyperliquid_liquidation_aggregation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var timestamp_timestamp_pb = require('./timestamp/timestamp_pb.js');
goog.object.extend(proto, timestamp_timestamp_pb);
goog.exportSymbol('proto.HyperliquidLiquidationAggregation', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.HyperliquidLiquidationAggregation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.HyperliquidLiquidationAggregation.repeatedFields_, null);
};
goog.inherits(proto.HyperliquidLiquidationAggregation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.HyperliquidLiquidationAggregation.displayName = 'proto.HyperliquidLiquidationAggregation';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.HyperliquidLiquidationAggregation.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.HyperliquidLiquidationAggregation.prototype.toObject = function(opt_includeInstance) {
  return proto.HyperliquidLiquidationAggregation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.HyperliquidLiquidationAggregation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.HyperliquidLiquidationAggregation.toObject = function(includeInstance, msg) {
  var f, obj = {
    timestamp: (f = msg.getTimestamp()) && timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f),
    coin: jspb.Message.getFieldWithDefault(msg, 2, ""),
    levelsList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 5)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.HyperliquidLiquidationAggregation}
 */
proto.HyperliquidLiquidationAggregation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.HyperliquidLiquidationAggregation;
  return proto.HyperliquidLiquidationAggregation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.HyperliquidLiquidationAggregation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.HyperliquidLiquidationAggregation}
 */
proto.HyperliquidLiquidationAggregation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCoin(value);
      break;
    case 5:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addLevels(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.HyperliquidLiquidationAggregation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.HyperliquidLiquidationAggregation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.HyperliquidLiquidationAggregation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.HyperliquidLiquidationAggregation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCoin();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLevelsList();
  if (f.length > 0) {
    writer.writePackedDouble(
      5,
      f
    );
  }
};


/**
 * optional Timestamp timestamp = 1;
 * @return {?proto.Timestamp}
 */
proto.HyperliquidLiquidationAggregation.prototype.getTimestamp = function() {
  return /** @type{?proto.Timestamp} */ (
    jspb.Message.getWrapperField(this, timestamp_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.Timestamp|undefined} value
 * @return {!proto.HyperliquidLiquidationAggregation} returns this
*/
proto.HyperliquidLiquidationAggregation.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.HyperliquidLiquidationAggregation} returns this
 */
proto.HyperliquidLiquidationAggregation.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.HyperliquidLiquidationAggregation.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string coin = 2;
 * @return {string}
 */
proto.HyperliquidLiquidationAggregation.prototype.getCoin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.HyperliquidLiquidationAggregation} returns this
 */
proto.HyperliquidLiquidationAggregation.prototype.setCoin = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated double levels = 5;
 * @return {!Array<number>}
 */
proto.HyperliquidLiquidationAggregation.prototype.getLevelsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 5));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.HyperliquidLiquidationAggregation} returns this
 */
proto.HyperliquidLiquidationAggregation.prototype.setLevelsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.HyperliquidLiquidationAggregation} returns this
 */
proto.HyperliquidLiquidationAggregation.prototype.addLevels = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.HyperliquidLiquidationAggregation} returns this
 */
proto.HyperliquidLiquidationAggregation.prototype.clearLevelsList = function() {
  return this.setLevelsList([]);
};


goog.object.extend(exports, proto);
