// source: option_open_interest_aggregation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var timestamp_timestamp_pb = require('./timestamp/timestamp_pb.js');
goog.object.extend(proto, timestamp_timestamp_pb);
goog.exportSymbol('proto.OptionOpenInterestAggregation', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.OptionOpenInterestAggregation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.OptionOpenInterestAggregation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.OptionOpenInterestAggregation.displayName = 'proto.OptionOpenInterestAggregation';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.OptionOpenInterestAggregation.prototype.toObject = function(opt_includeInstance) {
  return proto.OptionOpenInterestAggregation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.OptionOpenInterestAggregation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.OptionOpenInterestAggregation.toObject = function(includeInstance, msg) {
  var f, obj = {
    underlyingpriceclose: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    oiclose: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    timestamp: (f = msg.getTimestamp()) && timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.OptionOpenInterestAggregation}
 */
proto.OptionOpenInterestAggregation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.OptionOpenInterestAggregation;
  return proto.OptionOpenInterestAggregation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.OptionOpenInterestAggregation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.OptionOpenInterestAggregation}
 */
proto.OptionOpenInterestAggregation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setUnderlyingpriceclose(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOiclose(value);
      break;
    case 3:
      var value = new timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.OptionOpenInterestAggregation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.OptionOpenInterestAggregation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.OptionOpenInterestAggregation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.OptionOpenInterestAggregation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional double underlyingPriceClose = 1;
 * @return {number}
 */
proto.OptionOpenInterestAggregation.prototype.getUnderlyingpriceclose = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.OptionOpenInterestAggregation} returns this
 */
proto.OptionOpenInterestAggregation.prototype.setUnderlyingpriceclose = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.OptionOpenInterestAggregation} returns this
 */
proto.OptionOpenInterestAggregation.prototype.clearUnderlyingpriceclose = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.OptionOpenInterestAggregation.prototype.hasUnderlyingpriceclose = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional double oiClose = 2;
 * @return {number}
 */
proto.OptionOpenInterestAggregation.prototype.getOiclose = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.OptionOpenInterestAggregation} returns this
 */
proto.OptionOpenInterestAggregation.prototype.setOiclose = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.OptionOpenInterestAggregation} returns this
 */
proto.OptionOpenInterestAggregation.prototype.clearOiclose = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.OptionOpenInterestAggregation.prototype.hasOiclose = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Timestamp timestamp = 3;
 * @return {?proto.Timestamp}
 */
proto.OptionOpenInterestAggregation.prototype.getTimestamp = function() {
  return /** @type{?proto.Timestamp} */ (
    jspb.Message.getWrapperField(this, timestamp_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.Timestamp|undefined} value
 * @return {!proto.OptionOpenInterestAggregation} returns this
*/
proto.OptionOpenInterestAggregation.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.OptionOpenInterestAggregation} returns this
 */
proto.OptionOpenInterestAggregation.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.OptionOpenInterestAggregation.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto);
