/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: option_open_interest_aggregation.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./timestamp/timestamp";
import * as pb_1 from "google-protobuf";
export class OptionOpenInterestAggregation extends pb_1.Message {
    #one_of_decls: number[][] = [[1], [2]];
    constructor(data?: any[] | ({
        timestamp?: dependency_1.Timestamp;
    } & (({
        underlyingPriceClose?: number;
    }) | ({
        oiClose?: number;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("underlyingPriceClose" in data && data.underlyingPriceClose != undefined) {
                this.underlyingPriceClose = data.underlyingPriceClose;
            }
            if ("oiClose" in data && data.oiClose != undefined) {
                this.oiClose = data.oiClose;
            }
            if ("timestamp" in data && data.timestamp != undefined) {
                this.timestamp = data.timestamp;
            }
        }
    }
    get underlyingPriceClose() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set underlyingPriceClose(value: number) {
        pb_1.Message.setOneofField(this, 1, this.#one_of_decls[0], value);
    }
    get has_underlyingPriceClose() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get oiClose() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set oiClose(value: number) {
        pb_1.Message.setOneofField(this, 2, this.#one_of_decls[1], value);
    }
    get has_oiClose() {
        return pb_1.Message.getField(this, 2) != null;
    }
    get timestamp() {
        return pb_1.Message.getWrapperField(this, dependency_1.Timestamp, 3) as dependency_1.Timestamp;
    }
    set timestamp(value: dependency_1.Timestamp) {
        pb_1.Message.setWrapperField(this, 3, value);
    }
    get has_timestamp() {
        return pb_1.Message.getField(this, 3) != null;
    }
    get _underlyingPriceClose() {
        const cases: {
            [index: number]: "none" | "underlyingPriceClose";
        } = {
            0: "none",
            1: "underlyingPriceClose"
        };
        return cases[pb_1.Message.computeOneofCase(this, [1])];
    }
    get _oiClose() {
        const cases: {
            [index: number]: "none" | "oiClose";
        } = {
            0: "none",
            2: "oiClose"
        };
        return cases[pb_1.Message.computeOneofCase(this, [2])];
    }
    static fromObject(data: {
        underlyingPriceClose?: number;
        oiClose?: number;
        timestamp?: ReturnType<typeof dependency_1.Timestamp.prototype.toObject>;
    }): OptionOpenInterestAggregation {
        const message = new OptionOpenInterestAggregation({});
        if (data.underlyingPriceClose != null) {
            message.underlyingPriceClose = data.underlyingPriceClose;
        }
        if (data.oiClose != null) {
            message.oiClose = data.oiClose;
        }
        if (data.timestamp != null) {
            message.timestamp = dependency_1.Timestamp.fromObject(data.timestamp);
        }
        return message;
    }
    toObject() {
        const data: {
            underlyingPriceClose?: number;
            oiClose?: number;
            timestamp?: ReturnType<typeof dependency_1.Timestamp.prototype.toObject>;
        } = {};
        if (this.underlyingPriceClose != null) {
            data.underlyingPriceClose = this.underlyingPriceClose;
        }
        if (this.oiClose != null) {
            data.oiClose = this.oiClose;
        }
        if (this.timestamp != null) {
            data.timestamp = this.timestamp.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_underlyingPriceClose)
            writer.writeDouble(1, this.underlyingPriceClose);
        if (this.has_oiClose)
            writer.writeDouble(2, this.oiClose);
        if (this.has_timestamp)
            writer.writeMessage(3, this.timestamp, () => this.timestamp.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): OptionOpenInterestAggregation {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new OptionOpenInterestAggregation();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.underlyingPriceClose = reader.readDouble();
                    break;
                case 2:
                    message.oiClose = reader.readDouble();
                    break;
                case 3:
                    reader.readMessage(message.timestamp, () => message.timestamp = dependency_1.Timestamp.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): OptionOpenInterestAggregation {
        return OptionOpenInterestAggregation.deserialize(bytes);
    }
}
