// source: trade_side_agnostic_aggregation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var timestamp_timestamp_pb = require('./timestamp/timestamp_pb.js');
goog.object.extend(proto, timestamp_timestamp_pb);
goog.exportSymbol('proto.TradeSideAgnosticAggregation', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TradeSideAgnosticAggregation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.TradeSideAgnosticAggregation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.TradeSideAgnosticAggregation.displayName = 'proto.TradeSideAgnosticAggregation';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TradeSideAgnosticAggregation.prototype.toObject = function(opt_includeInstance) {
  return proto.TradeSideAgnosticAggregation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TradeSideAgnosticAggregation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TradeSideAgnosticAggregation.toObject = function(includeInstance, msg) {
  var f, obj = {
    open: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    high: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    low: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    close: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    volume: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    timestamp: (f = msg.getTimestamp()) && timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f),
    firsttimestamp: (f = msg.getFirsttimestamp()) && timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f),
    lasttimestamp: (f = msg.getLasttimestamp()) && timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TradeSideAgnosticAggregation}
 */
proto.TradeSideAgnosticAggregation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TradeSideAgnosticAggregation;
  return proto.TradeSideAgnosticAggregation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TradeSideAgnosticAggregation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TradeSideAgnosticAggregation}
 */
proto.TradeSideAgnosticAggregation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOpen(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setHigh(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLow(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setClose(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setVolume(value);
      break;
    case 6:
      var value = new timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 7:
      var value = new timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setFirsttimestamp(value);
      break;
    case 8:
      var value = new timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLasttimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TradeSideAgnosticAggregation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TradeSideAgnosticAggregation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TradeSideAgnosticAggregation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TradeSideAgnosticAggregation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpen();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getHigh();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getLow();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getClose();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getVolume();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getFirsttimestamp();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLasttimestamp();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional double open = 1;
 * @return {number}
 */
proto.TradeSideAgnosticAggregation.prototype.getOpen = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.TradeSideAgnosticAggregation} returns this
 */
proto.TradeSideAgnosticAggregation.prototype.setOpen = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double high = 2;
 * @return {number}
 */
proto.TradeSideAgnosticAggregation.prototype.getHigh = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.TradeSideAgnosticAggregation} returns this
 */
proto.TradeSideAgnosticAggregation.prototype.setHigh = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double low = 3;
 * @return {number}
 */
proto.TradeSideAgnosticAggregation.prototype.getLow = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.TradeSideAgnosticAggregation} returns this
 */
proto.TradeSideAgnosticAggregation.prototype.setLow = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double close = 4;
 * @return {number}
 */
proto.TradeSideAgnosticAggregation.prototype.getClose = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.TradeSideAgnosticAggregation} returns this
 */
proto.TradeSideAgnosticAggregation.prototype.setClose = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double volume = 5;
 * @return {number}
 */
proto.TradeSideAgnosticAggregation.prototype.getVolume = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.TradeSideAgnosticAggregation} returns this
 */
proto.TradeSideAgnosticAggregation.prototype.setVolume = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional Timestamp timestamp = 6;
 * @return {?proto.Timestamp}
 */
proto.TradeSideAgnosticAggregation.prototype.getTimestamp = function() {
  return /** @type{?proto.Timestamp} */ (
    jspb.Message.getWrapperField(this, timestamp_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.Timestamp|undefined} value
 * @return {!proto.TradeSideAgnosticAggregation} returns this
*/
proto.TradeSideAgnosticAggregation.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.TradeSideAgnosticAggregation} returns this
 */
proto.TradeSideAgnosticAggregation.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.TradeSideAgnosticAggregation.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional Timestamp firstTimestamp = 7;
 * @return {?proto.Timestamp}
 */
proto.TradeSideAgnosticAggregation.prototype.getFirsttimestamp = function() {
  return /** @type{?proto.Timestamp} */ (
    jspb.Message.getWrapperField(this, timestamp_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.Timestamp|undefined} value
 * @return {!proto.TradeSideAgnosticAggregation} returns this
*/
proto.TradeSideAgnosticAggregation.prototype.setFirsttimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.TradeSideAgnosticAggregation} returns this
 */
proto.TradeSideAgnosticAggregation.prototype.clearFirsttimestamp = function() {
  return this.setFirsttimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.TradeSideAgnosticAggregation.prototype.hasFirsttimestamp = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Timestamp lastTimestamp = 8;
 * @return {?proto.Timestamp}
 */
proto.TradeSideAgnosticAggregation.prototype.getLasttimestamp = function() {
  return /** @type{?proto.Timestamp} */ (
    jspb.Message.getWrapperField(this, timestamp_timestamp_pb.Timestamp, 8));
};


/**
 * @param {?proto.Timestamp|undefined} value
 * @return {!proto.TradeSideAgnosticAggregation} returns this
*/
proto.TradeSideAgnosticAggregation.prototype.setLasttimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.TradeSideAgnosticAggregation} returns this
 */
proto.TradeSideAgnosticAggregation.prototype.clearLasttimestamp = function() {
  return this.setLasttimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.TradeSideAgnosticAggregation.prototype.hasLasttimestamp = function() {
  return jspb.Message.getField(this, 8) != null;
};


goog.object.extend(exports, proto);
