/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: timestamp/timestamp.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class Timestamp extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        seconds?: number;
        nanoseconds?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("seconds" in data && data.seconds != undefined) {
                this.seconds = data.seconds;
            }
            if ("nanoseconds" in data && data.nanoseconds != undefined) {
                this.nanoseconds = data.nanoseconds;
            }
        }
    }
    get seconds() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set seconds(value: number) {
        pb_1.Message.setField(this, 1, value);
    }
    get nanoseconds() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set nanoseconds(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        seconds?: number;
        nanoseconds?: number;
    }): Timestamp {
        const message = new Timestamp({});
        if (data.seconds != null) {
            message.seconds = data.seconds;
        }
        if (data.nanoseconds != null) {
            message.nanoseconds = data.nanoseconds;
        }
        return message;
    }
    toObject() {
        const data: {
            seconds?: number;
            nanoseconds?: number;
        } = {};
        if (this.seconds != null) {
            data.seconds = this.seconds;
        }
        if (this.nanoseconds != null) {
            data.nanoseconds = this.nanoseconds;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.seconds != 0)
            writer.writeFixed32(1, this.seconds);
        if (this.nanoseconds != 0)
            writer.writeFixed32(2, this.nanoseconds);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Timestamp {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Timestamp();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.seconds = reader.readFixed32();
                    break;
                case 2:
                    message.nanoseconds = reader.readFixed32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Timestamp {
        return Timestamp.deserialize(bytes);
    }
}
